### ISSUE TITLE
problem downloading vic topo data

### ISSUE THREAD

**Issue by Ian-Almond** [mholling/nswtopo#12]
Hi Matthew - I am trying to use nswtopo with vic data. I have used successfully for nsw and tas but get an error downloading vic data. .. "in 'connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed OpenSSL::SSL::SSLError  I am having trouble uploading files. Thanks.   Ian

**Comment by rjtedge** [comment]
I have the same issue when trying to get content from the emap.depi.vic.gov.au server. I am pretty sure that the server has moved.
