### ISSUE TITLE
v1.1.4 problem with rastor

### ISSUE THREAD

**Issue by apiddington** [mholling/nswtopo#15]
Hi
v1.1.4 doesn't seem to create the rastor image properly.
Using the config attached the png and jpg only have the gridlines. The pdf has the map image as well.
Running the same config with v1.1 all formats are OK.
OS is Linux.
Cheers

[nswtopo.cfg.txt](https://github.com/mholling/nswtopo/files/107646/nswtopo.cfg.txt)

**Comment by apiddington** [comment]
Have just re-tested with phantomjs v2.1.1.
Still not working, but now produces a question mark graphic.
![western arthurs](https://cloud.githubusercontent.com/assets/16930169/12634538/7cee178e-c5ce-11e5-82ec-8fb2b02fe0f5.png)

**Comment by mholling** [comment]
Yep you are right, that doesn't work. I will put in a fix for that.

But really, the raster topo layers are just for comparison. Why don't you make the vector map instead:

```
include:
- tas/tasveg
- tas/topographic
- grid
```

**Comment by apiddington** [comment]
Hi Matthew,

I often make both. The vector map is short on location names and the 
placement of peaks is often far from the actual peak. The vector map is 
better for navigation because the contours are much clearer and less 
cluttered, especially with the older tasmaps.

However this error occurs with either tasmap or tas/topographic. The map 
is generated correctly for pdf format, but not for png/jpeg.

Thanks very much for making your work available. I really appreciate 
using it for my bushwalking maps.

By the way I haven't had any success with downloading map layers for 
Victoria.

Regards
Andrew Piddington

**Comment by mholling** [comment]
Ah OK. Well in any event it should be fixed now, try 1.1.5. Interesting comment about the TAS placenames. They were the hardest bit.

The only states which work properly are NSW and TAS. The others are all works-in-progress, mostly because the data is not fully available.

**Comment by apiddington** [comment]
Hi Matthew,

Thanks. 1.1.5 did the trick.

Yes I suspected that VIC was lagging behind in making mapping data 
available via WMS. Pity. They just want to make money with their 
1:30,000 pay for downloads. These maps are dreadful with all the messy 
cadastre boundaries.

I like the ability to define styles for controls. It would be nice to 
have multiple controls (waypoints) with different styles as you can with 
tracks. I'm familar with Python, PHP and Perl, but I struggle with Ruby. 
Ah well.

Cheers
Andrew
