### ISSUE TITLE
Downloading Error - Service Not available

### ISSUE THREAD

**Issue by Tinkicka** [mholling/nswtopo#16]
Hi,

it seems that one of the services is no longer available and is causing the script to halt without completion. The following is the text of the service notification when you run the script:

Calculating map bounds...
Map details:
  name: 8627-3S-brindabella
  size: 908mm x 554mm
  scale: 1:25000
  rotation: 0.0 degrees
  extent: 22.7km x 13.9km
Downloading: nsw.topographic
  plantation-horticulture
  urban-areas
  contours-10m (2763 features)
  cliffs-excavation (20 features)
  sand (4 features)
  cadastre (113 features)
  swamps-inundation (1 feature)
  watercourses
Error: Service sixmaps/Hydrography/MapServer not found 

From this I deduced that all of the data relating to the list above 'watercourses' is still available.
I was successfully downloading maps last week, but this week get the error. I have linked to the NSW Hydrography site using WMS via QGis and ARCMAP and it is still available.

I then attempted to change the address in the source files to what is shown in the address line in the WMS URL - NSW_Hydrography, but to no avail.

Can someone check if this service is still available via this script?

Thanks

Brett

**Comment by ondrejivanic** [comment]
There is more: Hydrography, Guras, and LPILocal are gone.

I've tried to replace Hydrography -> NSW_Hydrography (and folder is "public") but then I had to comment out the following sections to get script working:

- waterfalls
- reefs-rocks
- caves-pinnacles
- LPILocal fallback from the "roads" section
- and 'guras' section from the "roads" section

**Comment by maustrap** [comment]
Commit b9f138 fixed it. Thanks heaps, Matt! :)

**Comment by Tinkicka** [comment]
Thanks for making the necessary changes to the code to fix the original problem......

However, post July 1 2016 there have been a number of changes to NSW government websites, with NSW LPI and associated organisations being moved in a big way. 

Tonight when running the code (5 different areas of the state), it hangs on the nsw.topo-extras module and will not complete. The error returned is:

Error: 
Unable to perform query. Please check your parameters.

When I go to the web address for this service all I get is an IIS7 welcome page. It would appear that this service has probably moved to another URL, but trying to find it is not easy with the new moves.

Any suggestions????

Brett

**Comment by Tinkicka** [comment]
False alarm, the service is back up again tonight and it appears has not been affected by any move of URL's.

Brett
