### ISSUE TITLE
V1.1.7 Feature Issue

### ISSUE THREAD

**Issue by Tinkicka** [mholling/nswtopo#18]
Hi Matt (and others....),

it looks like something has changed again with the services. I had some scripts running overnight and from 0000 to 0500 all was well. After 0500 things became a little problematic. I checked the output from the run and quite a few after this time were incomplete because the nsw.topographic.json file was missing. This evening I ran one again in terminal mode and this is what I found:

Calculating map bounds...
Map details:
  name: 8826-3S-snowball
  size: 903mm x 554mm
  scale: 1:25000
  rotation: 0.0 degrees
  extent: 22.6km x 13.9km
Downloading: nsw.topographic
  plantation-horticulture
  urban-areas
  contours-10m (2715 features)
  cliffs-excavation (13 features)
  sand (25 features)
  cadastre (170 features)
  swamps-inundation (17 features)
  watercourses (2927 features)
  stock-dams (90 features)
  pondage
  coastline
  water-areas (39 features)
  levees
  dam-batters
  dam-walls-spillways
  waterfalls
  mangroves-intertidal
  reefs-rocks (8208 features)

As you can see, the reefs-rocks feature is a little large (I actually stopped the script at this point), especially when this map is about 50KM inland from the coast!

I went back to using the V1.1.6 script (and source folder and values.rb file) and everything works fine on this same map. 

I am not quite up to understanding the script just yet (but I'm working on it) so I am not going to try and figure out a solution.

Regards,

Brett

**Comment by elena** [comment]
Hi Matt (and also others),

I've been generating maps and loving them using this script for a couple of years now and have just encountered my first problem, which is similar to Brett's problem.

Generating JSON is timing out on "waterfalls" when using 1.1.7

The output is straight forward, it's just kept adding to the feature count for many hours. The output is as follows:
```
No layers specified. Adding nsw/topographic by default.
Calculating map bounds...
Map details:
  name: Tidbinbilla
  size: 410mm x 285mm
  scale: 1:25000
  rotation: 0.0 degrees
  extent: 10.3km x 7.1km
Downloading: nsw.topographic
  plantation-horticulture (3 features)
  urban-areas
  contours-10m (654 features)
  cliffs-excavation (42 features)
  sand (1 feature)
  cadastre (12 features)
  swamps-inundation
  watercourses (770 features)
  stock-dams (20 features)
  pondage
  coastline
  water-areas (17 features)
  levees
  dam-batters
  dam-walls-spillways
  waterfalls (13402 features)
```
[note this was the second time I ran the script with these parameters, the first time  `waterfalls` reached a count of ~2K before I killed it, in this second run this was around 4 hours before being killed]

Upon running the script with v1.1.6, the output is as follows:
```
Map details:
  name: Tidbinbilla
  size: 410mm x 285mm
  scale: 1:25000
  rotation: 0.0 degrees
  extent: 10.3km x 7.1km
Downloading: nsw.topographic
  plantation-horticulture (3 features)
  urban-areas
  contours-10m (654 features)
  cliffs-excavation (42 features)
  sand (1 feature)
  cadastre (12 features)
  swamps-inundation
  watercourses
Error: Service sixmaps/Hydrography/MapServer not found 
Creating: relief, 343x238 @ 30.0 m/px
Compositing: nsw.topographic
Failed to render nsw.topographic: source file not found at _[location]_
```
Same as Brett: Tidbinbilla actually isn't known for a voluminous number of waterfalls.

**Comment by elena** [comment]
Ah, luckily I did make a mistake initially and *successfully* generate a map -- although it was very narrow.

The successful generation output looks as follows:
```
Calculating map bounds...
Map details:
  name: Tidbinbilla
  size: 76mm x 285mm
  scale: 1:25000
  rotation: 0.0 degrees
  extent: 1.9km x 7.1km
Downloading: nsw.topographic
  plantation-horticulture (1 feature)
  urban-areas
  contours-10m (101 features)
  cliffs-excavation
  sand
  cadastre (11 features)
  swamps-inundation
  watercourses (191 features)
  stock-dams (30 features)
  pondage
  coastline
  water-areas (10 features)
  levees
  dam-batters
  dam-walls-spillways
  waterfalls
  mangroves-intertidal
  reefs-rocks
  rocky-shore
  breakwaters
  caves-pinnacles
  road-tunnels
  railway-tunnels
  wharves-ramps-slipways
  runways
  perimeters
  fences
  conveyors
  floodways
  roads (61 features)
  railways
  road-bridges (1 feature)
  railway-bridges
  gates-grids (5 features)
  tanks
  buildings (16 features)
  railway-stations
  spot-heights (6 features)
  beacons
  towers
  yards-quarries-windmills (1 feature)
  state-border
  relative-heights
  feature-names (2 features)
  place-names
Compositing: nsw.topographic
  plantation-horticulture
  contours-10m
  cadastre
  watercourses
  stock-dams
  water-areas
  roads
  road-bridges
  gates-grids
  buildings
  spot-heights
  yards-quarries-windmills
Styling: nsw.topographic
  plantation-horticulture
  contours-10m
  cadastre
  watercourses
  stock-dams
  water-areas
  roads
  road-bridges
  gates-grids
  buildings
  spot-heights
  yards-quarries-windmills
Compositing: labels
Styling: labels
  nsw.topographic
```
nb. This lacked the warning message `No layers specified. Adding nsw/topographic by default.`, but some failed attempts also lacked this warning so probably a red-herring.

This lead me to think the success/failure was influenced by the size of the map. 

So I started experimenting with different widths and even more interestingly at a certain size stopped getting tripped up on `waterfalls` and started getting tripped up on `reef-rocks`! (just to be clear: Just like Brett did!):

```
Calculating map bounds...
Map details:
  name: Tidbinbilla
  size: 156mm x 285mm
  scale: 1:25000
  rotation: 0.0 degrees
  extent: 3.9km x 7.1km
Downloading: nsw.topographic
  plantation-horticulture (3 features)
  urban-areas
  contours-10m (204 features)
  cliffs-excavation
  sand (1 feature)
  cadastre (12 features)
  swamps-inundation
  watercourses (307 features)
  stock-dams (19 features)
  pondage
  coastline
  water-areas (5 features)
  levees
  dam-batters
  dam-walls-spillways
  waterfalls
  mangroves-intertidal
  reefs-rocks (1222 features)^C
```

Sadly failure still occurred on a map that was narrower than the successful map.

This leads me to think that there is perhaps a specific feature on the failing map that is causing it to fail. 

In my case a feature between 148.959173 and 148.946092.

The 2 different `cfg` details are:

**success**:
```
scale: 25000
name: Tidbinbilla
latitudes:
- -35.406860
- -35.471090
longitudes:
- 148.959173
- 148.980288

```

**fail**:
```
scale: 25000
name: Tidbinbilla
latitudes:
- -35.406860
- -35.471090
longitudes:
- 148.959173
- 148.946092
```

I'm not sure how to turn off water-based-features to work around this (so sadly the bushwalk tomorrow is going to lack custom maps).

This is as far as I can take it today, but hopefully this helps!

I'm so grateful for this project nonetheless! Hopefully it continues to go well!

nswtopo <3

**Comment by elena** [comment]
Right, managed to work around the problem. Still may fork and add commit, if useful.

The problem seemed to be with the `definition` of 3 `features`.

Removing the `definitions` from `features` allowed the map to be generated, albeit without those features (but I'd rather a map without reef-rocks and cave-pinnacles etc than no map at all).

Here's my diff:
```
diff --git a/sources/nsw/topographic.yml b/sources/nsw/topographic.yml
index 609d481..1aa0635 100644
--- a/sources/nsw/topographic.yml
+++ b/sources/nsw/topographic.yml
@@ -152,7 +152,6 @@ features:
     - alternativelabel
   waterfalls:
     name: Waterfalls_springs
-    definition: ancillaryhydrotype = 6
     rotate: symbolrotation
     label: generalname
   mangroves-intertidal:
@@ -164,7 +163,6 @@ features:
     where: classsubtype IN (4,5)
     category: classsubtype
   - name: Caves_Pinnacles
-    definition: classsubtype IN (4,5)
     category: classsubtype
   - source: poi
     name: Points Of Interest
@@ -197,7 +195,6 @@ features:
     name: Caves_Pinnacles
     category: classsubtype
     label: generalname
-    definition: classsubtype IN (1,2,6)
   road-tunnels:
     source: rfs
     name: RoadSegment
```

Removing these 3 lines allowed me to run the script on my original coords no worries. Cheers!

**Comment by elena** [comment]
BTW @mholling thank you so much for the project! Apparently you're in Canberra? If so, should you ever come down to Guild in Bailey's Corner, I'm the owner there and would be stoked to give you a beer (or equivalent) to say thanks. (Just ask for Elena)

**Comment by Tinkicka** [comment]
Looks like it is working again now.....(had some time off the air and getting NBN hooked up....)

thanks

Brett
