### ISSUE TITLE
Services are moving

### ISSUE THREAD

**Issue by thejuan** [mholling/nswtopo#20]
Hi Adam,

Thank you for your feedback concerning our services and apps, Geoscience Australia is continuously trying to improve and provide the best service as possible for national spatial information. In regards to your query, we have been progressively migrating its services over to new infrastructure, and the dem_s_1s service is now available at: http://services.ga.gov.au/gis/rest/services/DEM_SRTM_1Second/MapServer

A list of the location of the new services is also available at: http://services.ga.gov.au/

Apologies for any inconvenience this may have caused, I hope this helps to answer your question?

Kind Regards,

Richelle Spry 
A/Team Leader – Foundation Products and Services
Spatial Applications Section | National Location Information Branch
Environmental Geoscience Division |  GEOSCIENCE AUSTRALIA

**Comment by WherezWally** [comment]
They've moved again!   The above link generates:
`Error: 301 "Moved Permanently"`

I believe the new link might be:
`http://services.ga.gov.au/site_9/rest/services/DEM_SRTM_1Second/MapServer/3`

However it generates the following error:
```
Creating: relief, 122x111 @ 30.0 m/px
c:/Carto/nswtopo-1.4/lib/nswtopo/relief_source.rb:41:in `fetch': key not found: "objectIds" (KeyError)
        from c:/Carto/nswtopo-1.4/lib/nswtopo/relief_source.rb:41:in `get_raster'
        from c:/Carto/nswtopo-1.4/lib/nswtopo/raster_renderer.rb:22:in `block in create'
        from c:/Carto/nswtopo-1.4/lib/helpers/dir.rb:4:in `block in mktmppath'
        from C:/Carto/Ruby23-x64/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
        from c:/Carto/nswtopo-1.4/lib/helpers/dir.rb:3:in `mktmppath'
        from c:/Carto/nswtopo-1.4/lib/nswtopo/raster_renderer.rb:21:in `create'
        from c:/Carto/nswtopo-1.4/lib/nswtopo.rb:229:in `block in run'
        from c:/Carto/nswtopo-1.4/lib/nswtopo.rb:227:in `each'
        from c:/Carto/nswtopo-1.4/lib/nswtopo.rb:227:in `run'
        from nswtopo:24:in `<main>'
```
Maybe the script needs to generate a temporary Key/Token before it can access the DEM data?
