### ISSUE TITLE
New VIC servers for wfs (and ArcGIS)

### ISSUE THREAD

**Issue by rjtedge** [mholling/nswtopo#30]
Vic gov are changing to a different server for the wfs content. The new server is 
http://services.land.vic.gov.au/catalogue/publicproxy/guest/dv_geoserver/wfs . 

I updated this in  vic/topographic.yml and changed the layer names from VMELEV.EL_CONTOUR to VMELEV_EL_CONTOUR as appears to be the new convention. I ran the script without error but get blank map.svg. 

Any idea why this is not working? 

The new wfs server has far more content from what I can see (including much of the ArcGIS - emap - content which no longer worjs)

**Comment by rjtedge** [comment]
I'm aware from my computer at the moment but was having a poke around on the new http://services.land.vic.gov.au/catalogue/publicproxy/guest/dv_geoserver/wfs. 

Looking into this further I am thinking it has to do with the new schema of xml from the wfs server. The old server responded with  
```
<wfs:member>
     <sii:VMELEV.EL_CONTOUR>
        <sii:SHAPE>
          <gml:posList>
          </gml:posList>
        </sii:SHAPE>
     </sii:VMELEV.EL_CONTOUR>
```
The new one looks like 
```
<wfs:member>
     <sii:VMELEV.EL_CONTOUR>
     </sii:VMELEV.EL_CONTOUR>
     <sii:SHAPE>
         <gml:posList>
         </gml:posList>
     </sii:SHAPE>
```

I'm assuming - without testing -  that changing feature_source.rb line 255 from 
`xml.elements.each("wfs:FeatureCollection/wfs:member/#{namespace}:#{type_name}") do |member|`
to 
`xml.elements.each("wfs:FeatureCollection/wfs:member") do |member|`

would fix some of the issues?

**Comment by rjtedge** [comment]
Not sure if anyone is interested, but the fix was easier than expected. 

1. Change the wfs server to http://services.land.vic.gov.au/catalogue/publicproxy/guest/dv_geoserver/wfs  in the sources/vic/topographic.yml file (line 16)

2. delete line 245 in lib/nswtopo/feature_source.rb

Update the features in sources/vic/topographic.yml to wfs features from services.land.vic.gov.au/catalogue/publicproxy/guest/dv_geoserver/wfs?request=getCapabilities 

I'll try to get an updated vic/topographic.yml  file later

**Comment by Tinkicka** [comment]
Hi rjtedge,

I have been trying to implement your fix to access the Vic data but to no avail. 

Can you provide an updated vic/topographic.yml file to the code?

thanks

Tinkicka

**Comment by rjtedge** [comment]
Hi, 

I've got a repo set up for the vicmaps [here]( https://github.com/rjtedge/victopo). It is not perfect but should do the job as a starting places for tinkering with. Have a look at the [map](https://github.com/rjtedge/victopo/tree/master/map) folder for a small example of Mt Sterling area.  

Let me know if you have any issues.

**Comment by Tinkicka** [comment]
Hi,

thanks for the link - all working now. 

thanks for you work.

Tinkicka

**Comment by Tinkicka** [comment]
Hi Rob,

I have just tried to construct some victopo maps but it appears that the servers have been changed again and it hangs when getting data. Any ideas on how to fix this?

Tinkicka (Brett)

**Comment by rjtedge** [comment]
No at a computer at the moment, but do you know which server has been changed?

**Comment by Tinkicka** [comment]
It is hanging immediately after all the vegetation is downloaded, so I think it is the vic/topographic server.

**Comment by rjtedge** [comment]
Ok back at my computer. It's been a while since I looked at this, but now I remember that this repo has moved a long way off working for the Vic servers - at least for me. I took it offline and made significant tweaks to make it work. I just uploaded it here - https://github.com/rjtedge/victopomaps/ 

The map/ folder has a small example as well as the cfg and control files that made it work. 

Hope this helps

**Comment by Tinkicka** [comment]
Hi Rob,

thanks for the update however I cannot get it to run on my machine. I get the following error:

_Traceback (most recent call last):
	4: from /home/brett/Maps/victopo/bin/nswtopo:18:in `<main>'
	3: from /home/brett/Maps/victopo/bin/nswtopo:18:in `require_relative'
	2: from /home/brett/Maps/victopo/lib/nswtopo.rb:15:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- active_support/all (LoadError)_

Any suggestions? It still runs fine with accessing the NSW data.

Brett
