### ISSUE TITLE
Non Standard Central Meridian

### ISSUE THREAD

**Issue by jnflint** [mholling/nswtopo#33]
The maps are projected using the centre line of the map as the central meridian.
This is not normal as the maps should in my view use the standard UTM meridians for the zone the map is in.
The grid on the other hand is correctly projected using the standard UTM central meridians.
(Otherwise the grid convergence would always be 0 deg at the centre line)
I am not sure if having the grid and map have different central meridians make any perceptible difference but to me it makes all the parameters such as coordinates and origin from the output of gdalinfo nonsensical without complicated conversion. 
You can see the numbers listed in the bounding coordinates are not the same as the grid references on the map.

Currently I re-project each map using the standard GDA94 EPSG codes with gdalwarp
gdalwarp -t_srs EPSG:28356 <imgin> <imgout>  for GDA94 zone 56
gdalwarp -t_srs EPSG:28355 <imgin> <imgout>  for GDA94 zone 55
etc

This also updates the coordinate system in the file metadata to something standard so that other software can more easily inter-operate.
eg:
PROJCS["GDA94 / MGA zone 56",
    GEOGCS["GDA94",
        DATUM["Geocentric_Datum_of_Australia_1994",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","6283"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4283"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",153],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",10000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","28356"]]

I would like the software to use standard UTM conventions.

**Comment by mholling** [comment]
Nope, the custom transverse mercator projection is needed for the map to be north-aligned. No issue with this projection as far as compatibility, any GIS software should understand it. Avenza loads it no problem.
