### ISSUE TITLE
Contour generated Relief for VIC

### ISSUE THREAD

**Issue by rjtedge** [mholling/nswtopo#34]
Hi, 

I love the new approach to generating relief images based on the contour data. Does anyone know how to make this work for the Vic contour data? 

Cheers
Rob

**Comment by rjtedge** [comment]
Not sure if people are interested, but I found a way to do the contour data generated hill shading for vic maps (using the contour data from vic gov sources). I'm happy to post if people are interested.

**Comment by Tinkicka** [comment]
Hi Rob,

I have just tried to construct some victopo maps but it appears that the servers have been changed and it hangs when getting data. Any ideas on how to fix this?

Tinkicka (Brett)
