### ISSUE TITLE
Map rotation of +/-45 degrees does not work

### ISSUE THREAD

**Issue by tombrennan06** [mholling/nswtopo#37]
Map rotation of exactly +/-45 degrees does not work as the rotation/translation logic in **vector_renderer.rb** doesn't handle it correctly. In theory you would end up with a divide by 0 error. In practice, there is imprecision, which just results in garbage translation numbers.

So the final output layers are in the wrong location in the SVG.

Not sure if this is the right approach (I have little idea about Ruby), but I ended up replacing:
```
if t >= 0
	y = (t * (h * t - w) / d).abs
	x = (t * y).abs
else
	x = -(t * (h + w * t) / d).abs
	y = -(t * x).abs
end
```
with
```
if CONFIG.map.rotation == 45.0
	x = 1000.0 * CONFIG.map.extents.first / CONFIG.map.scale / 2.0
	y = 1000.0 * CONFIG.map.extents.first / CONFIG.map.scale / 2.0
elsif CONFIG.map.rotation == -45.0
	x = -1000.0 * CONFIG.map.extents.last / CONFIG.map.scale / 2.0
	y = -1000.0 * CONFIG.map.extents.last / CONFIG.map.scale / 2.0
elsif t >= 0
	y = (t * (h * t - w) / d).abs
	x = (t * y).abs
else
	x = -(t * (h + w * t) / d).abs
	y = -(t * x).abs
end
```

**Comment by mholling** [comment]
No problems with 45° rotation in version 2.0.0
