### ISSUE TITLE
-> Garmin svg

### ISSUE THREAD

**Issue by Gergyl** [mholling/nswtopo#7]
Nice tool Matthew, and nice maps.  I'd like to be able to make a Garmin vector map of the result (.img).  The usual route is via Polish format (.mp) and GPSMapEdit or Global Mapper and then cGPSmapper.  The issue is that none of those do svg import.  Suggestions?

Maybe Global Mapper can read pdf vectors?

**Comment by thejuan** [comment]
I'd love to get this into basecamp as well.
the KMZ is not comptaible with basecamp, it only supports JPG's in the KMZ
Still looking for a route from GeoTiff to Garmin....
